GET http://localhost:3001/genres

###

GET http://localhost:3001/videogamesname?name=


###

GET http://localhost:3001/videogames

###

GET http://localhost:3001/videogames/2ca0b56d-5041-4f8d-af7a-9c1d588c57b8

###

POST http://localhost:3001/videogames
Content-Type: application/json 

{"Nombre":"Wild Rift",
"Descripcion":"Un juego vicioso", 
"Plataformas":"Android e ios", "Imagen":"bhiobhiobuyhiobuhyio.jpg", 
"Rating":"5",
"FechaLanzamiento":"15/05/2019",
"Genero":["Action","Shooter"]
}
