GET http://localhost:3001/genres

###

GET http://localhost:3001/videogamesname?name=


###

GET http://localhost:3001/videogames

###

GET http://localhost:3001/videogames/7b7e4e5b-da42-43ba-8d5a-a0cb4e5463ee

###

POST http://localhost:3001/videogames
Content-Type: application/json 

{"Nombre":"Wild Rift",
"Descripcion":"Un juego vicioso", 
"Plataformas":"Android e ios", "Imagen":"bhiobhiobuyhiobuhyio.jpg", 
"Rating":"5",
"FechaLanzamiento":"15/05/2019",
"Genero":["Action","Shooter"]
}
